### ISSUE TITLE
Focus Problem

### ISSUE THREAD

**Issue by gig71** [AtomFry/BigBoxAutoPlay#1] opened 2022-01-17 18:59 UTC
Hi, I love the Idea of an autoplay plugin for bigbox.
It could be very useful for Arcade cabinet owners!
I just tested it, and seem that when I start bigbox
bigbox has the focus and the autoplayed game rest in background.
I have to press alt+tab to chenge the focus.
Could it be fixed ?

Thanks.

**Comment by AtomFry** [comment] 2022-01-17 20:37
> Hi, I love the Idea of an autoplay plugin for bigbox.
> 
> It could be very useful for Arcade cabinet owners!
> 
> I just tested it, and seem that when I start bigbox
> 
> bigbox has the focus and the autoplayed game rest in background.
> 
> I have to press alt+tab to chenge the focus.
> 
> Could it be fixed ?
> 
> 
> 
> Thanks.

Thanks for letting me know about this issue. Are you experiencing this every time?  I am unable to reproduce this behavior. Is there a particular emulator and game that this happened with?

**Comment by gig71** [comment] 2022-01-17 20:47
Tanks for your fast answer.
Yes, i tested not much bot some games, and it always happens!
And if i can provide a suggestion, would be cool to provide a plugin for launchbox that can configure the autoplay json.
maybe with a right click on a game
 a sub menu with items like
 set this as autoplay.
 set random game as autoplay from this platform/playlist
 remove the autoplay.

and so on...

Just an idea!
thanks again

**Comment by AtomFry** [comment] 2022-01-17 22:13
> Tanks for your fast answer.
> Yes, i tested not much bot some games, and it always happens!

Could you give me an example of an emulator and game that this has happened with?  I am unable reproduce it at the moment so I'd like to test with the same emulator and game you're testing with.  

Regarding a setup screen, I agree that would be nice.  It's on my backlog as a nice to have :)

**Comment by gig71** [comment] 2022-01-17 23:22
Hi.
Done a bit more testing.
Looks like that:
with autoplaytype set to

specificgame - all works right and the game has the focus
tried many times and loks like it works.

but when i change the autoplaytype to every random type
then bigbox gui has the focus and the game is in background.
tested many times.

Hope you can reproduce it.

**Comment by AtomFry** [comment] 2022-01-18 02:02
> Hi. Done a bit more testing. Looks like that: with autoplaytype set to
> 
> specificgame - all works right and the game has the focus tried many times and loks like it works.
> 
> but when i change the autoplaytype to every random type then bigbox gui has the focus and the game is in background. tested many times.
> 
> Hope you can reproduce it.

I'm still not able to reproduce it.  I understand the issue is occurring for you when you set the AutoPlayType to RandomGame.  Could you let me know an emulator/game where this happened?  Whether I try with RandomGame or with SpecificGame, the game is launching on top.  I have tested with MAME (standalone), RetroArch, Dolphin, PPSSPP.  So far, they all open on top for me.

**Comment by gig71** [comment] 2022-01-18 19:18
well, tested again.
Looks like with settings 
randomplatform

tested platform Nintendo Entertainment System

games 
Whomp 'em, 
Kid Niki 3
Jurassic park

give the problem

emulator used retroarch mesen core


i tested more, and for now it seems to happen always with the nes platform

**Comment by gig71** [comment] 2022-01-18 19:19
Just a question, i have a startup video folder to run video on startup.
Does it matter maybe?

**Comment by gig71** [comment] 2022-01-18 19:25
other thing I saw is that your plugin run even the games  marked as HIDE.

**Comment by gig71** [comment] 2022-01-18 19:33
And, I have a setup with marquee screen.
The marquee screen not show the game game marque but the big box actually category marquee.

**Comment by AtomFry** [comment] 2022-01-19 00:37
I will try with Retroarch Mesen, startup video, and marquee monitor

**Comment by gig71** [comment] 2022-01-20 19:29
Thanx

**Comment by AtomFry** [comment] 2022-01-21 13:03
I am able to reproduce this now when I use a longer startup video. I'm curious, how long is your startup video?  It seems to happen randomly for me but only if I use a long startup video. I will look into some options to work around it. In the meantime, could try a shorter startup video to work around the issue.

**Comment by gig71** [comment] 2022-01-23 09:00
Good to know that you are able to reproduce it.
When tested before my video lenght was 14 seconds.
Now I tried with a custom made shorter video (4 seconds), and even without a start video too.
To me it seems to happen Randomly.
Thanks.

Ah, I forgot to say that I have the launchbox folder ( games , videos, exes, all ) on a separate internal SSD drive .
Thanks again!

**Comment by AtomFry** [comment] 2022-01-23 14:29
> other thing I saw is that your plugin run even the games marked as HIDE.

I have released an update so games marked Hide and Broken are not selected when set to select a random game.  I'm still looking into options for the focus problem.

**Comment by AtomFry** [comment] 2022-01-25 03:12
@gig71 I think I have the launch behind fixed now by adding a configurable delay before launching the game.  A two second delay is working in my system to allow BigBox to get settled after the video completes and before the game gets launched. 
 Could you give the latest version a try?  

1. Grab the BigBoxAutoPlay.dll from the latest release from here: 
https://github.com/AtomFry/BigBoxAutoPlay/releases/tag/1.0.2

2. Copy that into your LaunchBox\Plugins folder and replace the existing DLL

3. Open the settings.json file in the LaunchBox\Plugins\BigBoxAutoPlay folder in notepad
4. Add the "DelayInSeconds" setting like this: 
```
{
  "AutoPlayType": "RandomGame",
  "OnlyFavorites": "false",
  "Playlist": "",
  "Platform": "",
  "GameTitle": "",
  "DelayInSeconds": "2"
}
```

5. Save the file and startup big box.

**Comment by gig71** [comment] 2022-01-26 12:30
YEAH !
Thanks Man!
With delayinsecond set to 8 for me is working very good!
It's a great plugin!

Now if I would be very fussy :-)   (But I'm Not !).
The thing that miss is that the marquee should reflect the game that ran.
I don't know if this is feasible.

Congratulation for this useful plugin.
I think it deserves more attention by the users !

And thanks for your support !

**Comment by AtomFry** [comment] 2022-01-26 16:28
Nice man, glad that is resolved. Next for this is to add a little configuration screen so you don't have to get into the JSON file. Since the focus issue is resolved, I'll close this issue. Can you create a separate issue and tell me more about the marquee problem if you think it's relevant?  The plugin is only launching a game so it shouldn't interfere with marquee. Maybe I need to select the game first and then open it so that the marquee is triggered.  I will look into it. Don't hesitate to let me know if you run into other problems or have other suggestions.

**Closed as completed** 2022-01-26 18:29 UTC
